language: python
python:
    - "3.6"
before_install:
    - cd backend
install:
    - pip install .
    - pip install flake8
script:
    - python setup.py test
    - flake8 flask_app
notifications:
    slack:
        secure: RffNV7NGuqqb35ysGMN2BxfcK2Pf152OpbHb2qYoxXY5VFBFqM7ysh5+wUPugunzElKLW0YvvbDxRUCFZATVidLd1tq0cCepOBBtA8jFP4KbN1mNlGdpBb+TzJ91ws3Xl7jRsFjqJJ6rGkm261nzbWp753JztHvqVDNdO/2GDGPP3OrAB7iT08YSZzG1fOMtAUQcaqjdDAiaLlvWekJeZQhKCaG9+bAl8p894vmB4eMsVmokxZgNi/Qcq8UCY1ekOmYcq7IhNJA632R7zH8mAWVQpqyxH3Jqggzhsk7eICfntzkEePJDxAeobzzIq/SYe8Zm6Dy7VROI5pCq5Ds1LkAgm3yFoAuNibaOulaGwwPhHdArDx0GXGsjI9CqXXnMSfX5tPCUEVUGyI9AcStQ/DWSgZxGLc+cmyyK3keJqDyz3sRPCkcLO53GyP/1eoRzl6uJcfRQez3HxiQOd710N15JSKKbqUsJ8LkkrpOfA5Nw8dcm+gIhpeoHhguFgo+uIavMmXyXvxyX0SJbIawGezIoU5VlEB/Ynw/x++Jt9teEgyAdKeEtg8ab6/7BLFcmPvCLooQeAIOrmwojOFsecyUpoEyxehqLXhwows5iKkx/GMSGIQ0thxFRjPHwgknAmVgMlG9iN7/f0oiK56hXCwBhgvJpwKNFEiUdzFu8jVQ=
